// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Portal.Data
{
    public partial class AlMohasebDBContext : DbContext
    {
        public AlMohasebDBContext()
        {
        }

        public AlMohasebDBContext(DbContextOptions<AlMohasebDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<MosbName> MosbName { get; set; }
        public virtual DbSet<MosbReasons> MosbReasons { get; set; }
        public virtual DbSet<MosbReceivePayments> MosbReceivePayments { get; set; }
        public virtual DbSet<MosbSpendMoney> MosbSpendMoney { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MosbName>(entity =>
            {
                entity.ToTable("MOSB_NAME");

                entity.HasIndex(e => e.CivilNumber, "IX_MOSB_NAME_CIVIL_NUMBER")
                    .IsUnique();

                entity.HasIndex(e => e.PhoneNumber, "IX_MOSB_NAME_PHONE_NUMBER")
                    .IsUnique();

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.CivilNumber)
                    .HasColumnType("integer(10)")
                    .HasColumnName("CIVIL_NUMBER");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasColumnName("NAME");

                entity.Property(e => e.PhoneNumber)
                    .HasColumnType("integer(8)")
                    .HasColumnName("PHONE_NUMBER");

                entity.Property(e => e.ReasonsId)
                    .HasColumnType("integer(10)")
                    .HasColumnName("REASONS_ID");

                entity.Property(e => e.RegisterDate)
                    .HasColumnType("varchar(255)")
                    .HasColumnName("REGISTER_DATE");

                entity.HasOne(d => d.Reasons)
                    .WithMany(p => p.MosbName)
                    .HasForeignKey(d => d.ReasonsId)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<MosbReasons>(entity =>
            {
                entity.ToTable("MOSB_REASONS");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasColumnType("varchar(255)")
                    .HasColumnName("NAME");
            });

            modelBuilder.Entity<MosbReceivePayments>(entity =>
            {
                entity.ToTable("MOSB_RECEIVE_PAYMENTS");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Amount)
                    .HasColumnType("float(10)")
                    .HasColumnName("AMOUNT");

                entity.Property(e => e.Date)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasColumnName("DATE");

                entity.Property(e => e.NameId)
                    .HasColumnType("integer(10)")
                    .HasColumnName("NAME_ID");

                entity.Property(e => e.ReasonsId)
                    .HasColumnType("integer(10)")
                    .HasColumnName("REASONS_ID");

                entity.HasOne(d => d.Name)
                    .WithMany(p => p.MosbReceivePayments)
                    .HasForeignKey(d => d.NameId)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Reasons)
                    .WithMany(p => p.MosbReceivePayments)
                    .HasForeignKey(d => d.ReasonsId)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<MosbSpendMoney>(entity =>
            {
                entity.ToTable("MOSB_SPEND_MONEY");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Amount)
                    .HasColumnType("float(10)")
                    .HasColumnName("AMOUNT");

                entity.Property(e => e.Date)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasColumnName("DATE");

                entity.Property(e => e.MosbReasonsid)
                    .HasColumnType("integer(10)")
                    .HasColumnName("MOSB_REASONSID");

                entity.Property(e => e.NameId)
                    .HasColumnType("integer(10)")
                    .HasColumnName("NAME_ID");

                entity.HasOne(d => d.MosbReasons)
                    .WithMany(p => p.MosbSpendMoney)
                    .HasForeignKey(d => d.MosbReasonsid)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Name)
                    .WithMany(p => p.MosbSpendMoney)
                    .HasForeignKey(d => d.NameId)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}