// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Portal.Data
{
    public partial class AlMohasebDBContext : DbContext
    {
        public AlMohasebDBContext()
        {
        }

        public AlMohasebDBContext(DbContextOptions<AlMohasebDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<MosbName> MosbName { get; set; }
        public virtual DbSet<MosbReasons> MosbReasons { get; set; }
        public virtual DbSet<MosbReceivePayments> MosbReceivePayments { get; set; }
        public virtual DbSet<MosbSpendMoney> MosbSpendMoney { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MosbName>(entity =>
            {
                entity.ToTable("MOSB_NAME");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.CivilNumber)
                    .HasColumnType("integer(10)")
                    .HasColumnName("CIVIL_NUMBER");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasColumnName("NAME");

                entity.Property(e => e.PhoneNumber)
                    .HasColumnType("integer(8)")
                    .HasColumnName("PHONE_NUMBER");

                entity.Property(e => e.RegisterDate)
                    .IsRequired()
                    .HasColumnType("varchar(255)")
                    .HasColumnName("REGISTER_DATE");

                entity.Property(e => e.SubscriptionAmount)
                    .HasColumnType("double(10)")
                    .HasColumnName("SUBSCRIPTION_AMOUNT");
            });

            modelBuilder.Entity<MosbReasons>(entity =>
            {
                entity.ToTable("MOSB_REASONS");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Amount)
                    .HasColumnType("double(10)")
                    .HasColumnName("AMOUNT");

                entity.Property(e => e.Date)
                    .IsRequired()
                    .HasColumnType("varchar(255)")
                    .HasColumnName("DATE");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasColumnType("varchar(255)")
                    .HasColumnName("NAME");
            });

            modelBuilder.Entity<MosbReceivePayments>(entity =>
            {
                entity.ToTable("MOSB_RECEIVE_PAYMENTS");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Amount)
                    .HasColumnType("double(10)")
                    .HasColumnName("AMOUNT");

                entity.Property(e => e.CreatedDate)
                    .HasColumnType("varchar(255)")
                    .HasColumnName("CREATED_DATE");

                entity.Property(e => e.Date)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasColumnName("DATE");

                entity.Property(e => e.Description)
                    .IsRequired()
                    .HasColumnType("varchar(255)")
                    .HasColumnName("DESCRIPTION");

                entity.Property(e => e.IsMonthly)
                    .HasColumnType("integer(1)")
                    .HasColumnName("IS_MONTHLY");

                entity.Property(e => e.IsPaid)
                    .HasColumnType("integer(1)")
                    .HasColumnName("IS_PAID");

                entity.Property(e => e.IsTransaction)
                    .HasColumnType("integer(1)")
                    .HasColumnName("IS_TRANSACTION");

                entity.Property(e => e.ModifiedDate)
                    .HasColumnType("varchar(255)")
                    .HasColumnName("MODIFIED_DATE");

                entity.Property(e => e.NameId)
                    .HasColumnType("integer(10)")
                    .HasColumnName("NAME_ID");

                entity.Property(e => e.OriginalAmount)
                    .HasColumnType("double(10)")
                    .HasColumnName("ORIGINAL_AMOUNT");

                entity.Property(e => e.ReasonsId)
                    .HasColumnType("integer(10)")
                    .HasColumnName("REASONS_ID");

                entity.Property(e => e.SpendMoneyTargetId)
                    .HasColumnType("integer(10)")
                    .HasColumnName("SPEND_MONEY_TARGET_ID");

                entity.HasOne(d => d.Name)
                    .WithMany(p => p.MosbReceivePayments)
                    .HasForeignKey(d => d.NameId)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.SpendMoneyTarget)
                    .WithMany(p => p.MosbReceivePayments)
                    .HasForeignKey(d => d.SpendMoneyTargetId);
            });

            modelBuilder.Entity<MosbSpendMoney>(entity =>
            {
                entity.ToTable("MOSB_SPEND_MONEY");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Amount)
                    .HasColumnType("double(10)")
                    .HasColumnName("AMOUNT");

                entity.Property(e => e.CreatedDate)
                    .HasColumnType("varchar(255)")
                    .HasColumnName("CREATED_DATE");

                entity.Property(e => e.Date)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasColumnName("DATE");

                entity.Property(e => e.Description)
                    .HasColumnType("varchar(255)")
                    .HasColumnName("DESCRIPTION");

                entity.Property(e => e.IsFixed)
                    .HasColumnType("integer(1)")
                    .HasColumnName("IS_FIXED");

                entity.Property(e => e.IsForReason)
                    .HasColumnType("integer(1)")
                    .HasColumnName("IS_FOR_REASON");

                entity.Property(e => e.IsPaid)
                    .HasColumnType("integer(1)")
                    .HasColumnName("IS_PAID");

                entity.Property(e => e.IsTransaction)
                    .HasColumnType("integer(1)")
                    .HasColumnName("IS_TRANSACTION");

                entity.Property(e => e.ModifiedDate).HasColumnName("MODIFIED_DATE");

                entity.Property(e => e.MonthlyAmount)
                    .HasColumnType("double(10)")
                    .HasColumnName("MONTHLY_AMOUNT");

                entity.Property(e => e.OriginalAmount)
                    .HasColumnType("double(10)")
                    .HasColumnName("ORIGINAL_AMOUNT");

                entity.Property(e => e.PersonId)
                    .HasColumnType("integer(10)")
                    .HasColumnName("PERSON_ID");

                entity.Property(e => e.ReasonsId)
                    .HasColumnType("integer(10)")
                    .HasColumnName("REASONS_ID");

                entity.Property(e => e.ReceivePaymentsTargetId)
                    .HasColumnType("integer(10)")
                    .HasColumnName("RECEIVE_PAYMENTS_TARGET_ID");

                entity.HasOne(d => d.Person)
                    .WithMany(p => p.MosbSpendMoney)
                    .HasForeignKey(d => d.PersonId)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Reasons)
                    .WithMany(p => p.MosbSpendMoney)
                    .HasForeignKey(d => d.ReasonsId);

                entity.HasOne(d => d.ReceivePaymentsTarget)
                    .WithMany(p => p.MosbSpendMoney)
                    .HasForeignKey(d => d.ReceivePaymentsTargetId);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}