// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Portal.Data
{
    public partial class AlMohasebDBContext : DbContext
    {
        public AlMohasebDBContext()
        {
        }

        public AlMohasebDBContext(DbContextOptions<AlMohasebDBContext> options)
            : base(options)
        {
        }

        public virtual DbSet<MonthlyReceivePayments> MonthlyReceivePayments { get; set; }
        public virtual DbSet<MonthlyReceiveReason> MonthlyReceiveReason { get; set; }
        public virtual DbSet<MosbName> MosbName { get; set; }
        public virtual DbSet<MosbReasons> MosbReasons { get; set; }
        public virtual DbSet<MosbReceivePayments> MosbReceivePayments { get; set; }
        public virtual DbSet<MosbSpendMoney> MosbSpendMoney { get; set; }
        public virtual DbSet<MosbSpendMoneyForReason> MosbSpendMoneyForReason { get; set; }
        public virtual DbSet<ReasonsSpendMoneyMapping> ReasonsSpendMoneyMapping { get; set; }
        public virtual DbSet<ReceivePaymentsReasonsMapping> ReceivePaymentsReasonsMapping { get; set; }
        public virtual DbSet<User> User { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<MonthlyReceivePayments>(entity =>
            {
                entity.ToTable("MONTHLY_RECEIVE_PAYMENTS");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Amount)
                    .HasColumnType("double(10)")
                    .HasColumnName("AMOUNT");

                entity.Property(e => e.Date)
                    .IsRequired()
                    .HasColumnType("varchar(255)")
                    .HasColumnName("DATE");

                entity.Property(e => e.IsPaid)
                    .HasColumnType("integer(1)")
                    .HasColumnName("IS_PAID");

                entity.Property(e => e.PersonId)
                    .HasColumnType("integer(10)")
                    .HasColumnName("PERSON_ID");

                entity.HasOne(d => d.Person)
                    .WithMany(p => p.MonthlyReceivePayments)
                    .HasForeignKey(d => d.PersonId)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<MonthlyReceiveReason>(entity =>
            {
                entity.ToTable("MONTHLY_RECEIVE_REASON");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.MonthlyReceivePaymentsId)
                    .HasColumnType("integer(10)")
                    .HasColumnName("MONTHLY_RECEIVE_PAYMENTS_ID");

                entity.Property(e => e.ReasonId)
                    .HasColumnType("integer(10)")
                    .HasColumnName("REASON_ID");

                entity.HasOne(d => d.MonthlyReceivePayments)
                    .WithMany(p => p.MonthlyReceiveReason)
                    .HasForeignKey(d => d.MonthlyReceivePaymentsId)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Reason)
                    .WithMany(p => p.MonthlyReceiveReason)
                    .HasForeignKey(d => d.ReasonId)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<MosbName>(entity =>
            {
                entity.ToTable("MOSB_NAME");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.CivilNumber)
                    .HasColumnType("integer(10)")
                    .HasColumnName("CIVIL_NUMBER");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasColumnType("varchar(100)")
                    .HasColumnName("NAME");

                entity.Property(e => e.PhoneNumber)
                    .HasColumnType("integer(8)")
                    .HasColumnName("PHONE_NUMBER");

                entity.Property(e => e.RegisterDate)
                    .IsRequired()
                    .HasColumnType("varchar(255)")
                    .HasColumnName("REGISTER_DATE");

                entity.Property(e => e.SubscriptionAmount)
                    .HasColumnType("double(10)")
                    .HasColumnName("SUBSCRIPTION_AMOUNT");
            });

            modelBuilder.Entity<MosbReasons>(entity =>
            {
                entity.ToTable("MOSB_REASONS");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Amount)
                    .HasColumnType("double(10)")
                    .HasColumnName("AMOUNT");

                entity.Property(e => e.Date)
                    .IsRequired()
                    .HasColumnType("varchar(255)")
                    .HasColumnName("DATE");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasColumnType("varchar(255)")
                    .HasColumnName("NAME");
            });

            modelBuilder.Entity<MosbReceivePayments>(entity =>
            {
                entity.ToTable("MOSB_RECEIVE_PAYMENTS");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Amount)
                    .HasColumnType("double(10)")
                    .HasColumnName("AMOUNT");

                entity.Property(e => e.Date)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasColumnName("DATE");

                entity.Property(e => e.NameId)
                    .HasColumnType("integer(10)")
                    .HasColumnName("NAME_ID");

                entity.Property(e => e.ReasonsId)
                    .HasColumnType("integer(10)")
                    .HasColumnName("REASONS_ID");

                entity.HasOne(d => d.Name)
                    .WithMany(p => p.MosbReceivePayments)
                    .HasForeignKey(d => d.NameId)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<MosbSpendMoney>(entity =>
            {
                entity.ToTable("MOSB_SPEND_MONEY");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Amount)
                    .HasColumnType("double(10)")
                    .HasColumnName("AMOUNT");

                entity.Property(e => e.Date)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasColumnName("DATE");

                entity.Property(e => e.MosbReasonsid)
                    .HasColumnType("integer(10)")
                    .HasColumnName("MOSB_REASONSID");

                entity.Property(e => e.NameId)
                    .HasColumnType("integer(10)")
                    .HasColumnName("NAME_ID");

                entity.HasOne(d => d.Name)
                    .WithMany(p => p.MosbSpendMoney)
                    .HasForeignKey(d => d.NameId)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<MosbSpendMoneyForReason>(entity =>
            {
                entity.ToTable("MOSB_SPEND_MONEY_FOR_REASON");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Amount)
                    .HasColumnType("double(10)")
                    .HasColumnName("AMOUNT");

                entity.Property(e => e.Date)
                    .IsRequired()
                    .HasColumnType("varchar(50)")
                    .HasColumnName("DATE");

                entity.Property(e => e.IsPaid)
                    .HasColumnType("integer(1)")
                    .HasColumnName("IS_PAID");

                entity.Property(e => e.PersonId)
                    .HasColumnType("integer(10)")
                    .HasColumnName("PERSON_ID");

                entity.Property(e => e.ReasonsId)
                    .HasColumnType("integer(10)")
                    .HasColumnName("REASONS_ID");

                entity.HasOne(d => d.Person)
                    .WithMany(p => p.MosbSpendMoneyForReason)
                    .HasForeignKey(d => d.PersonId)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.Reasons)
                    .WithMany(p => p.MosbSpendMoneyForReason)
                    .HasForeignKey(d => d.ReasonsId)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<ReasonsSpendMoneyMapping>(entity =>
            {
                entity.ToTable("REASONS_SPEND_MONEY_MAPPING");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.ReasonsId)
                    .HasColumnType("integer(10)")
                    .HasColumnName("REASONS_ID");

                entity.Property(e => e.SpendMoneyId)
                    .HasColumnType("integer(10)")
                    .HasColumnName("SPEND_MONEY_ID");

                entity.HasOne(d => d.Reasons)
                    .WithMany(p => p.ReasonsSpendMoneyMapping)
                    .HasForeignKey(d => d.ReasonsId)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.SpendMoney)
                    .WithMany(p => p.ReasonsSpendMoneyMapping)
                    .HasForeignKey(d => d.SpendMoneyId)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<ReceivePaymentsReasonsMapping>(entity =>
            {
                entity.ToTable("RECEIVE_PAYMENTS_REASONS_MAPPING");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.ReasonsId)
                    .HasColumnType("integer(10)")
                    .HasColumnName("REASONS_ID");

                entity.Property(e => e.ReceivePaymentsId)
                    .HasColumnType("integer(10)")
                    .HasColumnName("RECEIVE_PAYMENTS_ID");

                entity.HasOne(d => d.Reasons)
                    .WithMany(p => p.ReceivePaymentsReasonsMapping)
                    .HasForeignKey(d => d.ReasonsId)
                    .OnDelete(DeleteBehavior.ClientSetNull);

                entity.HasOne(d => d.ReceivePayments)
                    .WithMany(p => p.ReceivePaymentsReasonsMapping)
                    .HasForeignKey(d => d.ReceivePaymentsId)
                    .OnDelete(DeleteBehavior.ClientSetNull);
            });

            modelBuilder.Entity<User>(entity =>
            {
                entity.ToTable("USER");

                entity.Property(e => e.Id).HasColumnName("ID");

                entity.Property(e => e.Password)
                    .HasColumnType("integer(10)")
                    .HasColumnName("PASSWORD");

                entity.Property(e => e.Username)
                    .HasColumnType("integer(10)")
                    .HasColumnName("USERNAME");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}