// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Portal.Data
{
    public partial class MonthlyReceiveReason
    {
        public long Id { get; set; }
        public long MonthlyReceivePaymentsId { get; set; }
        public long ReasonId { get; set; }

        public virtual MonthlyReceivePayments MonthlyReceivePayments { get; set; }
        public virtual MosbReasons Reason { get; set; }
    }
}