// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Portal.Data
{
    public partial class MosbReceivePayments
    {
        public MosbReceivePayments()
        {
            ReceivePaymentsReasonsMapping = new HashSet<ReceivePaymentsReasonsMapping>();
        }

        public long Id { get; set; }
        public long NameId { get; set; }
        public string Date { get; set; }
        public double Amount { get; set; }
        public string Description { get; set; }
        public long ReasonsId { get; set; }
        public long IsMonthly { get; set; }
        public long IsPaid { get; set; }
        public long? IsTransaction { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedDate { get; set; }
        public string OtherName { get; set; }
        public double? OriginalAmount { get; set; }

        public virtual MosbName Name { get; set; }
        public virtual ICollection<ReceivePaymentsReasonsMapping> ReceivePaymentsReasonsMapping { get; set; }
    }
}