// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Portal.Data
{
    public partial class MosbTransferMoney
    {
        public long Id { get; set; }
        public double Amount { get; set; }
        public long FromNameId { get; set; }
        public long ToNameId { get; set; }
        public string Date { get; set; }
        public string Description { get; set; }

        public virtual MosbName FromName { get; set; }
        public virtual MosbName ToName { get; set; }
    }
}