// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Portal.Data
{
    public partial class MosbReasons
    {
        public MosbReasons()
        {
            MosbSpendMoney = new HashSet<MosbSpendMoney>();
            PersonReasonMapping = new HashSet<PersonReasonMapping>();
            ReceivePaymentsReasonsMapping = new HashSet<ReceivePaymentsReasonsMapping>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public double Amount { get; set; }
        public string Date { get; set; }

        public virtual ICollection<MosbSpendMoney> MosbSpendMoney { get; set; }
        public virtual ICollection<PersonReasonMapping> PersonReasonMapping { get; set; }
        public virtual ICollection<ReceivePaymentsReasonsMapping> ReceivePaymentsReasonsMapping { get; set; }
    }
}