// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Portal.Data
{
    public partial class MosbReasons
    {
        public MosbReasons()
        {
            MosbName = new HashSet<MosbName>();
            MosbReceivePayments = new HashSet<MosbReceivePayments>();
            MosbSpendMoney = new HashSet<MosbSpendMoney>();
        }

        public long Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<MosbName> MosbName { get; set; }
        public virtual ICollection<MosbReceivePayments> MosbReceivePayments { get; set; }
        public virtual ICollection<MosbSpendMoney> MosbSpendMoney { get; set; }
    }
}