// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Portal.Data
{
    public partial class MosbName
    {
        public MosbName()
        {
            MonthlyReceivePayments = new HashSet<MonthlyReceivePayments>();
            MosbReceivePayments = new HashSet<MosbReceivePayments>();
            MosbSpendMoney = new HashSet<MosbSpendMoney>();
            MosbSpendMoneyForReason = new HashSet<MosbSpendMoneyForReason>();
            PersonReasonMapping = new HashSet<PersonReasonMapping>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public long CivilNumber { get; set; }
        public long? PhoneNumber { get; set; }
        public string RegisterDate { get; set; }
        public double? SubscriptionAmount { get; set; }

        public virtual ICollection<MonthlyReceivePayments> MonthlyReceivePayments { get; set; }
        public virtual ICollection<MosbReceivePayments> MosbReceivePayments { get; set; }
        public virtual ICollection<MosbSpendMoney> MosbSpendMoney { get; set; }
        public virtual ICollection<MosbSpendMoneyForReason> MosbSpendMoneyForReason { get; set; }
        public virtual ICollection<PersonReasonMapping> PersonReasonMapping { get; set; }
    }
}