// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Portal.Data
{
    public partial class MosbSpendMoney
    {
        public MosbSpendMoney()
        {
            MosbReceivePayments = new HashSet<MosbReceivePayments>();
        }

        public long Id { get; set; }
        public long PersonId { get; set; }
        public long? ReasonsId { get; set; }
        public long IsPaid { get; set; }
        public long? IsForReason { get; set; }
        public string Date { get; set; }
        public double Amount { get; set; }
        public string Description { get; set; }
        public double? MonthlyAmount { get; set; }
        public long? IsTransaction { get; set; }
        public long? IsFixed { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedDate { get; set; }
        public long? ReceivePaymentsTargetId { get; set; }
        public double? OriginalAmount { get; set; }

        public virtual MosbName Person { get; set; }
        public virtual MosbReasons Reasons { get; set; }
        public virtual MosbReceivePayments ReceivePaymentsTarget { get; set; }
        public virtual ICollection<MosbReceivePayments> MosbReceivePayments { get; set; }
    }
}