// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Portal.Data
{
    public partial class MosbSpendMoney
    {
        public long Id { get; set; }
        public long NameId { get; set; }
        public string Date { get; set; }
        public double Amount { get; set; }
        public long MosbReasonsid { get; set; }

        public virtual MosbReasons MosbReasons { get; set; }
        public virtual MosbName Name { get; set; }
    }
}