// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Portal.Data
{
    public partial class MosbTransferMoney
    {
        public long Id { get; set; }
        public double Amount { get; set; }
        public long FromPersonId { get; set; }
        public long ToPersonId { get; set; }
        public string Date { get; set; }
        public string Description { get; set; }

        public virtual MosbReasons FromPerson { get; set; }
        public virtual MosbReasons ToPerson { get; set; }
    }
}