// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Portal.Data
{
    public partial class MosbSpendMoneyForReason
    {
        public long Id { get; set; }
        public long PersonId { get; set; }
        public long ReasonsId { get; set; }
        public long IsPaid { get; set; }
        public string Date { get; set; }
        public double Amount { get; set; }

        public virtual MosbName Person { get; set; }
        public virtual MosbReasons Reasons { get; set; }
    }
}