// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Portal.Data
{
    public partial class MosbReasons
    {
        public MosbReasons()
        {
            MonthlyReceiveReason = new HashSet<MonthlyReceiveReason>();
            MosbSpendMoneyForReason = new HashSet<MosbSpendMoneyForReason>();
            ReasonsSpendMoneyMapping = new HashSet<ReasonsSpendMoneyMapping>();
            ReceivePaymentsReasonsMapping = new HashSet<ReceivePaymentsReasonsMapping>();
        }

        public long Id { get; set; }
        public string Name { get; set; }
        public double Amount { get; set; }
        public string Date { get; set; }

        public virtual ICollection<MonthlyReceiveReason> MonthlyReceiveReason { get; set; }
        public virtual ICollection<MosbSpendMoneyForReason> MosbSpendMoneyForReason { get; set; }
        public virtual ICollection<ReasonsSpendMoneyMapping> ReasonsSpendMoneyMapping { get; set; }
        public virtual ICollection<ReceivePaymentsReasonsMapping> ReceivePaymentsReasonsMapping { get; set; }
    }
}