// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Portal.Data
{
    public partial class ReceivePaymentsReasonsMapping
    {
        public long Id { get; set; }
        public long ReceivePaymentsId { get; set; }
        public long ReasonsId { get; set; }

        public virtual MosbReasons Reasons { get; set; }
        public virtual MosbReceivePayments ReceivePayments { get; set; }
    }
}