// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Portal.Data
{
    public partial class User
    {
        public long Id { get; set; }
        public long Username { get; set; }
        public long Password { get; set; }
    }
}